name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run deployment hook script
        run: |
          ./deployment-hook.sh ${{ github.event_name }} ${{ github.ref }}
